<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Three Rings" />
    <meta name="keywords" content="advergames,advergame developer,advergaming,advergame development,online advergames,flash advergames,custom advergames,promotional game,online advertising idea,advertising game,adver-game,adver-games,advertisement game,advergame creator,web advergames,internet advergames" />
    <meta name="description" content="Advergames at Arkadium. Your source for an advergame developer, advergaming, advergame development and online advergames" />
    <meta name="robots" content="all" />
