<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Three Rings" />
    <meta name="keywords" content="Meez,Avatar,Icon,Personal Icon,3D,3D Avatar,3D Animation,Beenz,Beanz,IM,Instant Messenger,Blog,MySpace" />
    <meta name="description" content="At Meez.com, you can create unique 3D avatars that animate in minutes. Use them as your personal I.D. on IM, blogs, MySpace and other sites." />
    <meta name="robots" content="all" />
